require 'pry'
require 'rspec'
require './safe_require'

safe_require 'robot'
safe_require 'item'
safe_require 'weapon'
safe_require 'box_of_bolts'
safe_require 'laser'
safe_require 'plasma_cannon'
#safe_require 'heal_exception'
safe_require 'robot_already_dead_error'
safe_require 'unattackable_enemy'